"""Track member due payments

Revision ID: 010077e92966
Revises: c18fc046b164
Create Date: 2026-08-15 22:42:22.704672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010077e92966'
down_revision: Union[str, Sequence[str], None] = 'c18fc046b164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_dues', sa.Column('paid_amount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_dues', 'paid_amount')
    # ### end Alembic commands ###
