"""Add member settlement records

Revision ID: 488d0138d700
Revises: 0f15e1d251f5
Create Date: 2026-08-15 23:18:12.126283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '488d0138d700'
down_revision: Union[str, Sequence[str], None] = '0f15e1d251f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('contribution_balance', sa.Integer(), nullable=False),
    sa.Column('asset_share', sa.Integer(), nullable=False),
    sa.Column('goods_value', sa.Integer(), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=False),
    sa.Column('outstanding_dues', sa.Integer(), nullable=False),
    sa.Column('final_amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_settlements')
    # ### end Alembic commands ###
