"""sync death support and member due fields

Revision ID: 7180ec133767
Revises: 3706bf203b99
Create Date: 2026-08-19 00:29:43.979590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7180ec133767'
down_revision: Union[str, Sequence[str], None] = '3706bf203b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('death_supports', sa.Column('member_funded_amount', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('death_supports', sa.Column('qarz_e_hasana_amount', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('member_dues', sa.Column('due_type', sa.String(length=50), nullable=False, server_default=sa.text("'ordinary'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member_dues', 'due_type')
    op.drop_column('death_supports', 'qarz_e_hasana_amount')
    op.drop_column('death_supports', 'member_funded_amount')
    # ### end Alembic commands ###
